POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFubmkyIiwiaWQiOiI2M2UwZjI5MTVjNDMyMzg4ODAxYmU5NjEiLCJpYXQiOjE2NzU2ODc3NTN9.I6F4X8_2ApY7-Sy5T60SYHzNbQ5yNyvd4IM260sV3t4

{
   "author": "testataam",
   "title" : "toimiiko token",
    "url": "testi.fi",
    "likes": 1,
    "userId": "63e0f2915c432388801be961"
}